version: '3.3'

services:
  practice:
      container_name: practice
      image: practice/sasha:0.0.1-SNAPSHOT
      ports:
        - 8081:8080
      environment:
        spring.datasource.url: jdbc:h2:file:/opt/practice/database
      volumes:
        - type: volume
          source: practice
          target: /opt/practice

volumes:
  practice: {}
